name: ads_schools
description: "School Results App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter_dotenv: ^5.0.2
  camera: ^0.11.0+2
  cloud_firestore: ^5.6.0
  data_table_2: ^2.5.18
  dynamic_multi_step_form: ^1.1.5
  excel: ^4.0.6
  file_picker: ^8.1.6
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.4.0
  flutter:
    sdk: flutter
  flutter_stepindicator: ^0.1.7
  intl: ^0.19.0
  open_file: ^3.2.1
  path_provider: ^2.0.12
  pdf: ^3.10.0
  printing: ^5.11.0
  #pdf:
  #printing:
  qr_code_tools: ^0.1.0
  qr_flutter: ^4.1.0
  syncfusion_flutter_xlsio: ^25.1.42
  universal_html: ^2.2.4
  url_launcher: ^6.1.8
  vector_math: ^2.1.4
  qr_code_scanner: ^1.0.1
  provider: ^6.1.2
  fl_chart: ^0.70.2
  flutter_web_qrcode_scanner: ^1.1.1
  qr_bar_code_scanner_dialog: ^0.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test:

#dependency_overrides:
 # pdf:
  #  path: ../pdf
  #printing:
   # path: ../printing

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/

  fonts:
    - family: Bree_Serif
      fonts:
        - asset: fonts/Bree_Serif/BreeSerif-Regular.ttf
    - family: akeila
      fonts:
        - asset: fonts/akeila/Akeila.otf
    - family: aldyn-heart
      fonts:
        - asset: fonts/aldyn-heart/AldynHeart-R998A.otf
    - family: rogbold
      fonts:
        - asset: fonts/rogbold/Rogbold-3llGM.otf
    - family: roulleta
      fonts:
        - asset: fonts/roulleta/Rouletta.ttf
    - family: six-fence
      fonts:
        - asset: fonts/six-fence/SIX-FENCE.otf
    - family: lt-serif
      fonts:
        - asset: fonts/lt-serif/LT.SerifDemo.otf                                       
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-logo.png"
  min_sdk_android: 21
  web:
    generate: true
  windows:
    generate: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app-logo.png"
