name: ads_schools
description: "School Results App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  cloud_firestore: ^5.6.0
  data_table_2: ^2.5.18
  dynamic_multi_step_form: ^1.1.5
  excel: ^4.0.6
  file_picker: ^8.1.6
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_stepindicator: ^0.1.7
  intl: ^0.19.0
  open_file: ^3.2.1
  path_provider: ^2.0.12
  pdf:
  printing:
  syncfusion_flutter_xlsio: ^25.1.42
  universal_html: ^2.2.4
  url_launcher: ^6.1.8
  vector_math: ^2.1.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test:

dependency_overrides:
  pdf:
    path: ../pdf
  printing:
    path: ../printing

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-logo.png"
  min_sdk_android: 21
  web:
    generate: true
  windows:
    generate: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app-logo.png"
